Vagrant.configure("2") do |config|

  config.vm.box = "hypervv/Ubuntu2004"


  config.vm.provider "hyperv" do |hv|
    hv.cpus = 2
    hv.memory = 1024
    hv.maxmemory = 2048
    hv.linked_clone = true
  end


  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y iputils-ping avahi-daemon libnss-mdns unzip openjdk-17-jdk-headless
  SHELL


  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.11"


    db.vm.provision "shell", inline: <<-SHELL
      wget https://repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar
      java -cp h2-1.4.200.jar org.h2.tools.Server -web -webAllowOthers -tcp -tcpAllowOthers -ifNotExists > ~/h2-server.log 2>&1 &
    SHELL
  end


  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.10"


    web.vm.provision "shell", inline: <<-SHELL
      sudo apt install -y tomcat9 tomcat9-admin



      git clone https://github.com/tiagopereiraswitch/devops-23-24-JPE-1231861.git
      sudo chown -R vagrant:vagrant /home/vagrant/devops-23-24-JPE-1231861

      cd devops-23-24-JPE-1231861/CA2/part2
      chmod +x ./gradlew
      ./gradlew build
      nohup ./gradlew bootRun > /home/vagrant/spring-boot-app.log 2>&1 &
    SHELL
  end
end